export const internships = [
    {
        id: 1,
        title: "Praktikum Softwareentwicklung",
        description: "IT-Dienstleister für individuelle Software, Prozessdigitalisierung und IT-Beratung. Du arbeitest in einem agilen Team an Webanwendungen mit Java und Vue.js.",
        company: "Konzept Informationssysteme GmbH",
        location: "Meersburg",
        category: "SOFTWARE_DEVELOPMENT",
        salary: 950,
        duration: 6,
        logoUrl: "/konzept.png",
    },
    {
        id: 2,
        title: "Praktikum Systemengineering",
        description: "Anbieter von Testsystemen für Halbleiter. Du unterstützt bei Qualitätstests, Automatisierung und Entwicklung innovativer Mess-Systeme.",
        company: "Advantest Europe GmbH",
        location: "Böblingen",
        category: "SYSTEM_ENGINEERING",
        salary: 1100,
        duration: 6,
        logoUrl: "/advantest.png",
    },
    {
        id: 3,
        title: "Praktikum Data Analyst",
        description: "Du analysierst Geschäftsdaten, erstellst Dashboards mit Power BI und entwickelst Reports für interne und externe Kunden.",
        company: "Konzept Informationssysteme GmbH",
        location: "Konstanz",
        category: "DATA_ANALYST",
        salary: 900,
        duration: 5,
        logoUrl: "/konzept.png",
    },
    {
        id: 4,
        title: "Praktikum Cyber Security",
        description: "Mitarbeit im Security-Team: Penetration Testing, Schwachstellen-Analyse und Härtung der internen IT-Systeme.",
        company: "Advantest Europe GmbH",
        location: "Böblingen",
        category: "CYBER_SECURITY",
        salary: 1050,
        duration: 6,
        logoUrl: "/advantest.png",
    },
];